### ISSUE TITLE
wowa not importing my addons

### ISSUE THREAD

**Issue by skandix** [antiwinter/wowa#35]
I just installed wowa with npm, but when I wanted to import my addons, it didn't find any when I did wowa import. Been using twitch app with lutris, so I knew i had addons in there.

![Screen Capture_select-area_20200517141031](https://user-images.githubusercontent.com/2757177/82145035-31469d00-9848-11ea-936d-7abf7d96c347.jpg)

I looked into the folders, and it seems that wowa only looks for AddOns and not Addons, I can just rename the folder, but I feel that defeated the purpose of using a cli for handling wow addons :)

**Comment by antiwinter** [comment]
I'm afraid this cannot be properly supported. **AddOns** and **Addons** are all good for windows applications (**wow.exe** or **wowa** for windows). But when **wowa** is running on a case sensitive filesystem, it cannot recognize the nondefault folder name (Yes, **AddOns** is the default folder name generated by **wow.exe**).

My explanation is that **Twitch** runs with **lutris** and **wow.exe** runs with **lutris**, so they don't have this problem. But **wowa** in your case is running on **Linux**, so it cannot recognize that folder.

I can just support **Addons** in **wowa** but that is not a proper way. Because **Addons**, **aDDons** or **addoNS** are all valid names for **wow.exe** with **Lutris**. If **wowa** supports **Addons**, it should support all of them and **iNterfaces/addOns** and **INTterfacS/ADDONS** etc,. too many.

Your folder name must be accidentally changed and the best idea, for now, is to rename it to the default one.
