### ISSUE TITLE
some github addons not working

### ISSUE THREAD

**Issue by gcaliber** [antiwinter/wowa#9]
An example is github.com/Mokilok22/RareAware

When I try to add it it says not available...

Mokilok22/RareAware [github] not availabe [skipped]

It seems like it has to do with all the files being at top level rather than in a subfolder.

Aslo, I just noticed there is a typo in available there.

**Comment by antiwinter** [comment]
Yes, that is because that repo does not have any tags/releases. So **wowa** cannot determine the correct addon version. And clone from master directly without any tags may be unstable.

But I am considering adding this clone-directly-from-master feature if tags/releases are unavailable, so one can install an addon anyway.

**Comment by antiwinter** [comment]
Supported in 1.2.2
